name: NPM Publish
on: 
  push:
    tags:
      - '*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: print version number
        run: echo ${{ env.RELEASE_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: configure git
        run: |
          git config user.email "info@plattar.com"
          git config user.name "Plattar"
      - name: set pre-release version
        run: npm version --prefix plattar-ar-adapter ${{ env.RELEASE_VERSION }}
      - name: write version.js
        run: rm -rf plattar-ar-adapter/src/version.ts && echo 'export default "${{ env.RELEASE_VERSION }}";' > plattar-ar-adapter/src/version.ts
      - name: copy README
        run: cp README.md plattar-ar-adapter/README.md
      - name: copy graphics
        run: cp -R graphics plattar-ar-adapter/
      - name: NPM Build
        run: npm run --prefix plattar-ar-adapter clean:build
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: ./plattar-ar-adapter/package.json
          token: ${{ secrets.NPM_PUBLISH_KEY }}
          access: 'public'
      - name: Plattar CDN Cache
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_REGION }}
          SOURCE_DIR: './plattar-ar-adapter/build/es2019'
          DEST_DIR: '/public-sdk/plattar-ar-adapter/${{env.RELEASE_VERSION}}/'
  purge-cache:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/npm/@plattar/plattar-ar-adapter/build/es2015/plattar-ar-adapter.min.js
            https://cdn.jsdelivr.net/npm/@plattar/plattar-ar-adapter/build/es2019/plattar-ar-adapter.min.js
            https://cdn.jsdelivr.net/npm/@plattar/plattar-ar-adapter/build/es2015/plattar-ar-adapter.js
            https://cdn.jsdelivr.net/npm/@plattar/plattar-ar-adapter/build/es2019/plattar-ar-adapter.js
